src/resource_hub/api/urls.py
from django.conf.urls import url
from django.urls import include, path

from resource_hub.core.hooks import UrlHook

app_name = 'api'
api_urls = UrlHook()
urlpatterns = [
    path('', include(api_urls.get())),
]

src/resource_hub/core/urls.py
import django.contrib.auth.views as dj_auth
from django.urls import include, path, re_path
from django.views.i18n import JavaScriptCatalog
from resource_hub.api.urls import api_urls
from resource_hub.control.urls import control_urls
from resource_hub.core.views import api, auth, control, site

from .hooks import UrlHook

finance_urls = UrlHook()
finance_urls.register([
    path('bank-accounts/', control.FinanceBankAccounts.as_view(),
         name='finance_bank_accounts'),
    path('payment-methods/manage/',
         control.FinancePaymentMethodsManage.as_view(), name='finance_payment_methods_manage'),
    path('payment-methods/manage/<int:pk>/', control.FinancePaymentMethodsEdit.as_view(
    ), name='finance_payment_methods_edit'),
    path('payment-methods/add/<str:scope>/',
         control.FinancePaymentMethodsAdd.as_view(), name='finance_payment_methods_add'),
    path('contracts/credited/', control.FinanceContractsCredited.as_view(),
         name='finance_contracts_credited'),
    path('contracts/debited/', control.FinanceContractsDebited.as_view(),
         name='finance_contracts_debited'),
    path('contracts/manage/<int:pk>/', control.FinanceContractsManageDetails.as_view(),
         name='finance_contracts_manage_details'),
    path('contract-procedures/manage/', control.FinanceContractProceduresManage.as_view(),
         name='finance_contract_procedures_manage'),
    path('contract-procedures/create/', control.FinanceContractProceduresCreate.as_view(),
         name='finance_contract_procedures_create'),
    path('invoices/outgoing/', control.FinanceInvoicesOutgoing.as_view(),
         name='finance_invoices_outgoing'),
    path('invoices/incoming/', control.FinanceInvoicesIncoming.as_view(),
         name='finance_invoices_incoming'),
])
control_urls.register([
    # account
    path('', control.Home.as_view(), name='home'),
    path('account/settings/<str:scope>/',
         control.AccountSettings.as_view(),
         name='account_settings'),
    path('account/security/<str:scope>/',
         control.AccountSecurity.as_view(),
         name='account_security'),
    path('account/notifications/settings/',
         control.NotificationsSettings.as_view(),
         name='notifications_settings'),
    path('account/verification/resend', auth.VerificationResend.as_view(),
         name='account_verification_resend'),

    # notifications
    path('notifications/', control.Notifications.as_view(), name='notifications'),

    # finance
    path('finance/', include(finance_urls.get())),

    # organizations
    path('organizations/manage/',
         control.OrganizationsManage.as_view(),
         name='organizations_manage'),
    path('organizations/create/',
         control.OrganizationsCreate.as_view(),
         name='organizations_create'),
    path('organizations/manage/<int:organization_id>/profile/edit/<str:scope>/',
         control.OrganizationsProfileEdit.as_view(),
         name='organizations_profile_edit'),
    path('organizations/manage/<int:organization_id>/members/',
         control.OrganizationsMembers.as_view(),
         name='organizations_members'),
    path('organizations/manage/<int:organization_id>/members/add/',
         control.OrganizationsMembersAdd.as_view(),
         name='organizations_members_add'),
    path('organizations/manage/<int:organization_id>/profile/',
         control.OrganizationsProfile.as_view(),
         name='organizations_profile'),

    # locations
    path('locations/manage/', control.LocationsManage.as_view(),
         name='locations_manage'),
    path('locations/create/', control.LocationsCreate.as_view(),
         name='locations_create'),
    path('locations/manage/<int:pk>/', control.LocationsEdit.as_view(),
         name='locations_edit'),
])

api_urls.register([
    path('users/search/', api.UserSearch.as_view(), name='search_users'),
    path('actors/list', api.ActorList.as_view(), name='actor_list'),
    path('actors/change',
         api.ActorChange.as_view(), name='actor_change'),
    path('organizations/<int:organization_pk>/members/change', api.OrganizationMembersChange.as_view(),
         name='organizations_members_change'),
    path('locations/search/', api.Locations.as_view(),
         name='locations_search'),
    path('contracts/list', api.ContractsList.as_view(), name='contracts_list'),
    path('notifications/list', api.NotificationsList.as_view(),
         name='notifications_list'),
    path('notifications/unread', api.NotificationsUnread.as_view(),
         name='notifications_unread'),
    path('notifications/mark/read/', api.NotificationsMarkRead.as_view(),
         name='notifications_mark_read'),
])

app_name = 'core'
urlpatterns = [
    # site
    path('', site.index, name='index'),
    path('home/', site.Home.as_view(), name='home'),
    path('bug/', site.ReportBug.as_view(), name='report_bug'),
    path('language/', site.Language.as_view(), name='language'),
    path('terms/', site.Terms.as_view(), name='terms'),
    path('imprint/', site.Imprint.as_view(), name='imprint'),
    path('privacy/', site.DataPrivacyStatement.as_view(), name='privacy'),
    path('locations/<slug:slug>/',
         site.LocationsProfile.as_view(), name='locations_profile'),
    path('actor/<slug:slug>/',
         site.ActorProfile.as_view(),
         name='actor_profile'),

    # path
    path('register/', auth.Register.as_view(), name='register'),
    path('login/', auth.custom_login, name='login'),
    path('logout/', dj_auth.LogoutView.as_view(
        template_name='core/logout.html'), name='logout'),
    re_path(r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
            auth.Verify.as_view(), name='verify'),
    path('password/reset/', dj_auth.PasswordResetView.as_view(
        template_name='core/password_reset.html', success_url='/password/reset/done/', email_template_name='core/mail_password_reset.html'), name='password_reset'),
    path('password/reset/done/', dj_auth.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html', ), name='password_reset_done'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', dj_auth.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html', success_url='/password/reset/complete/'), name='password_reset_confirm'),
    path('password/reset/complete/', dj_auth.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html')),
    path('actor/set', auth.SetRole.as_view(), name='actor_set'),


    # locale stuff
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n.js', JavaScriptCatalog.as_view(
        packages=['recurrence']), name='jsi18n'),
]

src/resource_hub/items/urls.py
from django.urls import path

from resource_hub.core.urls import api_urls, control_urls

from . import api, views

app_name = 'items'

api_urls.register([
    path('items/', api.Items.as_view(), name='items'),
    path('items/<int:pk>/bookings/', api.Bookings.as_view(), name='item_bookings'),
    path('items/<slug:owner_slug>/<slug:item_slug>/feed.ics',
         api.ICSFeed(), name='items_ics_feed'),
])

control_urls.register([
    path('items/manage/', views.ItemsManage.as_view(), name='items_manage'),
    path('items/manage/<int:pk>/',
         views.ItemsEdit.as_view(), name='items_edit'),
    path('items/create/', views.ItemsCreate.as_view(), name='items_create'),
    path('items/contract-procedures/create', views.ContractProceduresCreate.as_view(),
         name='items_contract_procedures_create'),
    path('items/contract-procedures/edit/<int:pk>/', views.ContractProceduresEdit.as_view(),
         name='items_contract_procedures_edit'),
    path('items/bookings/credited', views.ItemBookingsCredited.as_view(),
         name='item_bookings_credited'),
    path('items/bookings/debited', views.ItemBookingsDebited.as_view(),
         name='item_bookings_debited'),
])

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:owner_slug>/<slug:item_slug>/',
         views.ItemsDetails.as_view(), name='details'),
    path('<slug:owner_slug>/<slug:item_slug>/book',
         views.ItemBookingsCreate.as_view(), name='book'),
    path('bookings/<int:pk>/', views.ItemBookings.as_view(),
         name='bookings'),
]

src/resource_hub/plugins/sepa/urls.py
from django.urls import path

from resource_hub.core.urls import finance_urls

from .views import (OpenPayments, SEPAMandateDetails, XMLFilesCreate,
                    XMLFilesManage)

app_name = 'sepa'
finance_urls.register([
    path('sepa/mandate/<int:mandate_pk>/<int:contract_pk>/',
         SEPAMandateDetails.as_view(), name='sepa_mandate'),
    path('sepa/manage/', XMLFilesManage.as_view(),
         name='finance_sepa_files_manage'),
    path('sepa/create/', XMLFilesCreate.as_view(),
         name='finance_sepa_files_create'),
    path('sepa/payments/open/', OpenPayments.as_view(),
         name='finance_sepa_open_payments'),
])

urlpatterns = [
]

src/resource_hub/urls.py
"""
resource_hub URL Configuration

"""
import importlib

from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

for app in apps.get_app_configs():
    if importlib.util.find_spec(app.name + '.urls'):
        importlib.import_module(app.name + '.urls')

urlpatterns = [
    # apps
    path('', include('resource_hub.core.urls')),
    path('api/', include('resource_hub.api.urls')),
    path('control/', include('resource_hub.control.urls')),
    path('venues/', include('resource_hub.venues.urls')),
    path('items/', include('resource_hub.items.urls')),
    path('workshops/', include('resource_hub.workshops.urls')),

    # external apps
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/resource_hub/items/templates/items/_contract_overview.html
{% load i18n %}

{% for item in contract.items.all %}
<h2>{% trans 'Item details' %}</h2>
<div class="ui stackable two column grid">
    <div class="column">
        <h3>{{ item.name }}</h3>
        {% include 'items/_item_info.html' %}
    </div>
    <div class="column">
        <img src="{{ item.thumbnail.url }}" alt="{% trans 'Item thumbnail' %}">
    </div>
</div>
{% endfor %}

src/resource_hub/items/templates/items/_item_calendar.html
{% load i18n %}
{% load static %}
{% load sekizai_tags %}


{% addtoblock 'extra_head' %}
{% get_current_language as LANG %}
<link href="{% static 'fullcalendar/main.min.css' %}" rel="stylesheet">
<link href="{% static 'fullcalendar/daygrid/main.min.css' %}" rel="stylesheet">
<link href="{% static 'fullcalendar/timegrid/main.min.css' %}" rel="stylesheet">
<link href="{% static 'fullcalendar/list/main.min.css' %}" rel="stylesheet">

<script src="{% static 'fullcalendar/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/daygrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/timegrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/list/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/interaction/main.min.js' %}"></script>
{% if item %}
<script>
    var calendar = null;
    document.addEventListener('DOMContentLoaded', function () {
        var locale = '{{ LANG }}';
        var calendarEl = document.getElementById('calendar');

        calendar = new FullCalendar.Calendar(calendarEl, {
            events: function (info, successCallback, failureCallback) {
                $.get("{% url 'api:item_bookings' pk=item.pk %}", {
                    start: info.startStr,
                    end: info.endStr
                }).done(function (data) {
                    successCallback(
                        data.results
                    )
                })
            },
            plugins: ['list', 'dayGrid', 'interaction'],
            locale: locale,
            selectable: true,
            unselectAuto: false,
            unselectCancel: 'fc-button ',
            select: function (selectionInfo) {
                dtPickerStart.datetimepicker({ value: selectionInfo.start })
                dtPickerEnd.datetimepicker({ value: selectionInfo.end })
            },
            defaultView: 'dayGridMonth',
            contentHeight: 'auto',
            header: { left: 'title', center: '', right: 'dayGridMonth,listWeek prev,next' },
            buttonText: {
                'dayGridMonth': "{% trans 'month' %}",
                'listWeek': "{% trans 'week' %}"

            },
        });

        calendar.render();
    });
</script>
{% endif %}
{% endaddtoblock %}


<div class="calendar" id='calendar'></div>
<div class="section-container">
    <div class="ui left action input">
        <button class="ui teal left labeled icon copy button" data-content="{% trans 'Link copied!' %}" data-tooltip="
            {% trans 'Copy link' %}" onclick="copy(this)">
            {% trans 'Subscribe' %}
            <i class="rss icon"></i>
        </button>
        <input id="value-to-copy" type="text"
            value="{{ request.scheme }}://{{ request.get_host }}{% url 'api:items_ics_feed' owner_slug=item.owner.slug item_slug=item.slug %}">
    </div>
    <div>
        <span class="help">{% trans 'Add this iCal-feed to your calendar app (Google calendar, Nextcloud etc.)' %}
        </span>
    </div>
</div>

src/resource_hub/items/templates/items/_item_feed.html
{% load i18n %}
{% load sekizai_tags %}

{% include 'items/_item_feed_renderer.html' %}
{% addtoblock 'js' %}
<script>
    $(document).ready(function () {
        var item_feed = new BlockFeed("{% url 'api:items' %}", 'item-feed', render_item_feed);
        item_feed.create_feed();

        $('#filter-form').on('submit', function (e) {
            e.preventDefault();
            var name = $(this).find("input[name='search_query']").val();
            item_feed.create_feed({ name: name });
        });
    });
</script>
{% endaddtoblock %}

src/resource_hub/items/templates/items/_item_feed_renderer.html
{% load i18n %}
{% load sekizai_tags %}

{% include '_block_feed.html' with blocks='four' feed_id='item-feed' %}
{% addtoblock 'js' %}
<script id="item-template" type="text/template">
    <div class="column">
        <a id='card' class="ui fluid card" href="%href%">
            <div class="content">
                <img class="ui avatar image" src="%owner_thumbnail%" alt="{% trans 'Logo' %}"> %owner_name%
            </div>
            <div class="blurring dimmable image">
                <div class="ui dimmer">
                    <div class="content">
                        <div class="center">
                            <div class="ui inverted button">{% trans 'Details' %}</div>
                        </div>
                    </div>
                </div>
                <img class="thumbnail" src="%item_thumbnail%" alt="{% trans 'Thumbnail' %}">
            </div>
            <div class="ui placeholder">
                <div class="square image"></div>
            </div>
            <div class="content">
                <div class="header">%name%</div>
                <div class="meta">
                    <p><i class="map marker alternate icon"></i> %address_string%</p>
                </div>
            </div>
        </a>
    </div>
</script>
<script>
    function render_item_feed(data) {
        var template = document.getElementById("item-template");
        var templateHtml = template.innerHTML;
        var feed = '';
        $.each(data, function (i, item) {
            feed += templateHtml
                .replace(/%href%/g, item['href'])
                .replace(/%owner_name%/g, item.owner['name'])
                .replace(/%owner_thumbnail%/g, item.owner['thumbnail'])
                .replace(/%item_thumbnail%/g, item['thumbnail'])
                .replace(/%name%/g, item['name'])
                .replace(/%address_string%/g, item.location.address['address_string']);
        });
        return feed;
    }
</script>
{% endaddtoblock %}

src/resource_hub/items/templates/items/_item_info.html
{% load i18n %}

<div class="ui stackable two column grid">
    <div class="column">
        <div class="ui list">
            <div class="item">
                <div class="header">{% trans 'Category' %}</div>
                {{ item.get_category_display }}
            </div>
            <div class="item">
                <div class="header">{% trans 'Available quantity' %}</div>
                {{ item.quantity }}
            </div>
            {% if item.manufacturer %}
            <div class="item">
                <div class="header">
                    {% trans 'Manufacturer' %}
                </div>
                {{ item.manufacturer }}
            </div>
            {% endif %}
            {% if item.model %}
            <div class="item">
                <div class="header">
                    {% trans 'Model' %}
                </div>
                {{ item.model }}
            </div>
            {% endif %}
            {% if item.serial_no %}
            <div class="item">
                <div class="header">
                    {% trans 'Serial number' %}
                </div>
                {{ item.serial_no }}
            </div>
            {% endif %}
            {% if item.serial_no %}
            <div class="item">
                <div class="header">
                    {% trans 'Serial number' %}
                </div>
                {{ item.serial_no }}
            </div>
            {% endif %}
        </div>
    </div>
    <div class="column">
        <div class="ui list">
            <div class="item">
                <div class="header">
                    {% trans 'Base price' %}
                </div>
                {{ item.base_price }}
            </div>
            <div class="item">
                <div class="header">
                    {% trans 'Self pickup' %}
                </div>
                {{ item.get_self_pickup_display }}
            </div>
            <div class="item">
                <div class="header">
                    {% trans 'Unit' %}
                </div>
                {{ item.get_unit_display }}
            </div>
            {% if item.maximum_duration > 0 %}
            <div class="item">
                <div class="header">
                    {% trans 'Maximum lending duration' %}
                </div>
                {{ item.maximum_duration }}
            </div>
            {% endif %}
        </div>
    </div>
    <!-- <div class="header">{% trans 'Description' %}</div> -->
    <div>
        <div class="header">
            {% trans 'Description' %}
        </div>
        {{ item.description|safe }}
    </div>
</div>

src/resource_hub/items/templates/items/index.html
{% extends 'core/__base.html' %}
{% load i18n %}

{% block content %}
<div class="ui segment">
    <h5>{% trans 'Filters' %} <i class="filter icon"></i></h5>
    <form class="ui form" id="filter-form">
        <div class="ui icon input">
            <input id="search-venue" name="search_query" type="text" placeholder="{% trans 'search...' %}">
            <i class="search icon"></i>
        </div>
        <div class="float-container">
            <button class="ui right floated positive right labeled icon button" type="submit">
                {% trans 'Filter' %}
                <i class="filter icon"></i>
            </button>
        </div>
    </form>
</div>
{% include 'items/_item_feed.html' %}
{% endblock %}

src/resource_hub/items/templates/items/item_bookings_create.html
{% extends 'core/__base.html' %}
{% load i18n %}
{% load static %}
{% load custom_tags %}

{% block extra_head %}
<script src="{% url 'core:jsi18n' %}"></script>
{{ event_form.media }}
{% endblock %}

{% block not_in_container %}
<div class="main container large">
    <div class="ui stackable two column grid">
        <div class="seven wide column">
            <div class="ui horizontal section divider">{% trans 'Availability' %}</div>
            {% if item.unit == 'd' %}{% setvar 'Y-m-d' as format %}{% else %}{% setvar 'Y-m-d H:i' as format %}{% endif %}
            {% url 'api:item_bookings' pk=item.pk as event_url %}
            {% get_current_language as lang %}
            {% url 'api:items_ics_feed' owner_slug=item.owner.slug item_slug=item.slug as ics_url %}
            {% include '_calendar.html' with event_url=event_url lang=lang ics_url=ics_url format=format %}
        </div>
        <div class="nine wide column">
            {% get_current_language as lang %}
            {% url 'items:details' item_slug=item.slug owner_slug=item.owner.slug as url %}
            {% include '_back_button.html' with url=url %}
            <h1>
                {% trans 'Create item booking' %}
            </h1>

            <form class="ui form" method="POST" enctype="multipart/form-data">
                {% include '_form.html' with form=item_contract_form %}
                <div id="container">
                    {% include '_form.html' with form=item_form %}
                </div>
                <div class="section-container">
                    {% include 'core/_identity.html' with actor=actor %}
                    <button class="ui positive right labeled icon button" type="submit">
                        {% trans 'Check booking' %}
                        <i class="zoom-in icon"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/resource_hub/items/templates/items/item_details.html
{% extends 'core/__base.html' %}
{% load i18n %}

{% block not_in_container %}
<div class="container">
    <div class="location-image" style="background-image: url('{{ item.thumbnail_original.url }}')">
    </div>
</div>
<div class="main container large">
    <div class="ui stackable two column grid">
        <div class="eight wide column">
            <nav class="button-navigation">
                <a class="ui right labeled positive icon button"
                    href="{% url 'items:book' item_slug=item.slug owner_slug=item.owner.slug %}">
                    {% trans 'Lend' %}
                    <i class="calendar alternate outline icon"></i>
                </a>
                <a class="ui labeled right floated icon back button" href="{% url 'items:index' %}">
                    <i class="left arrow icon"></i>
                    {% trans 'Back' %}
                </a>
            </nav>
            <h1>{{ item.name }}</h1>
            {% include 'items/_item_info.html' %}

        </div>
        <div class="eight wide column">
            {% if item.location.is_public %}
            {% include 'core/_location_info.html' with location=item.location %}
            {% endif %}
        </div>
    </div>
    <div class="main container">
        <div class="section-container">
            {% if item.gallery.images.all %}
            <div class="ui horizontal section divider">{% trans 'Gallery' %}</div>
            {% include '_gallery.html' with gallery=item.gallery.images.all %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        $('.fluid.card .image').dimmer({ on: 'hover' });
    })
</script>
{% endblock %}

src/resource_hub/items/templates/items/location_profile.html
{% load i18n %}
{% load sekizai_tags %}

<div class="ui horizontal section divider">{% trans 'Items' %}</div>

{% include 'items/_item_feed_renderer.html' %}
<script>
    $(document).ready(function () {
        var item_feed = new BlockFeed('{% url "api:items" %}', 'item-feed', render_item_feed);
        item_feed.create_feed({ id: '{{ location.id }}' });
    });
</script>