src/resource_hub/api/urls.py
from django.conf.urls import url
from django.urls import include, path

from resource_hub.core.hooks import UrlHook

app_name = 'api'
api_urls = UrlHook()
urlpatterns = [
    path('', include(api_urls.get())),
]

src/resource_hub/core/urls.py
import django.contrib.auth.views as dj_auth
from django.urls import include, path, re_path
from django.views.i18n import JavaScriptCatalog
from resource_hub.api.urls import api_urls
from resource_hub.control.urls import control_urls
from resource_hub.core.views import api, auth, control, site

from .hooks import UrlHook

finance_urls = UrlHook()
finance_urls.register([
    path('bank-accounts/', control.FinanceBankAccounts.as_view(),
         name='finance_bank_accounts'),
    path('payment-methods/manage/',
         control.FinancePaymentMethodsManage.as_view(), name='finance_payment_methods_manage'),
    path('payment-methods/manage/<int:pk>/', control.FinancePaymentMethodsEdit.as_view(
    ), name='finance_payment_methods_edit'),
    path('payment-methods/add/<str:scope>/',
         control.FinancePaymentMethodsAdd.as_view(), name='finance_payment_methods_add'),
    path('contracts/credited/', control.FinanceContractsCredited.as_view(),
         name='finance_contracts_credited'),
    path('contracts/debited/', control.FinanceContractsDebited.as_view(),
         name='finance_contracts_debited'),
    path('contracts/manage/<int:pk>/', control.FinanceContractsManageDetails.as_view(),
         name='finance_contracts_manage_details'),
    path('contract-procedures/manage/', control.FinanceContractProceduresManage.as_view(),
         name='finance_contract_procedures_manage'),
    path('contract-procedures/create/', control.FinanceContractProceduresCreate.as_view(),
         name='finance_contract_procedures_create'),
    path('invoices/outgoing/', control.FinanceInvoicesOutgoing.as_view(),
         name='finance_invoices_outgoing'),
    path('invoices/incoming/', control.FinanceInvoicesIncoming.as_view(),
         name='finance_invoices_incoming'),
])
control_urls.register([
    # account
    path('', control.Home.as_view(), name='home'),
    path('account/settings/<str:scope>/',
         control.AccountSettings.as_view(),
         name='account_settings'),
    path('account/security/<str:scope>/',
         control.AccountSecurity.as_view(),
         name='account_security'),
    path('account/notifications/settings/',
         control.NotificationsSettings.as_view(),
         name='notifications_settings'),
    path('account/verification/resend', auth.VerificationResend.as_view(),
         name='account_verification_resend'),

    # notifications
    path('notifications/', control.Notifications.as_view(), name='notifications'),

    # finance
    path('finance/', include(finance_urls.get())),

    # organizations
    path('organizations/manage/',
         control.OrganizationsManage.as_view(),
         name='organizations_manage'),
    path('organizations/create/',
         control.OrganizationsCreate.as_view(),
         name='organizations_create'),
    path('organizations/manage/<int:organization_id>/profile/edit/<str:scope>/',
         control.OrganizationsProfileEdit.as_view(),
         name='organizations_profile_edit'),
    path('organizations/manage/<int:organization_id>/members/',
         control.OrganizationsMembers.as_view(),
         name='organizations_members'),
    path('organizations/manage/<int:organization_id>/members/add/',
         control.OrganizationsMembersAdd.as_view(),
         name='organizations_members_add'),
    path('organizations/manage/<int:organization_id>/profile/',
         control.OrganizationsProfile.as_view(),
         name='organizations_profile'),

    # locations
    path('locations/manage/', control.LocationsManage.as_view(),
         name='locations_manage'),
    path('locations/create/', control.LocationsCreate.as_view(),
         name='locations_create'),
    path('locations/manage/<int:pk>/', control.LocationsEdit.as_view(),
         name='locations_edit'),
])

api_urls.register([
    path('users/search/', api.UserSearch.as_view(), name='search_users'),
    path('actors/list', api.ActorList.as_view(), name='actor_list'),
    path('actors/change',
         api.ActorChange.as_view(), name='actor_change'),
    path('organizations/<int:organization_pk>/members/change', api.OrganizationMembersChange.as_view(),
         name='organizations_members_change'),
    path('locations/search/', api.Locations.as_view(),
         name='locations_search'),
    path('contracts/list', api.ContractsList.as_view(), name='contracts_list'),
    path('notifications/list', api.NotificationsList.as_view(),
         name='notifications_list'),
    path('notifications/unread', api.NotificationsUnread.as_view(),
         name='notifications_unread'),
    path('notifications/mark/read/', api.NotificationsMarkRead.as_view(),
         name='notifications_mark_read'),
])

app_name = 'core'
urlpatterns = [
    # site
    path('', site.index, name='index'),
    path('home/', site.Home.as_view(), name='home'),
    path('bug/', site.ReportBug.as_view(), name='report_bug'),
    path('language/', site.Language.as_view(), name='language'),
    path('terms/', site.Terms.as_view(), name='terms'),
    path('imprint/', site.Imprint.as_view(), name='imprint'),
    path('privacy/', site.DataPrivacyStatement.as_view(), name='privacy'),
    path('locations/<slug:slug>/',
         site.LocationsProfile.as_view(), name='locations_profile'),
    path('actor/<slug:slug>/',
         site.ActorProfile.as_view(),
         name='actor_profile'),

    # path
    path('register/', auth.Register.as_view(), name='register'),
    path('login/', auth.custom_login, name='login'),
    path('logout/', dj_auth.LogoutView.as_view(
        template_name='core/logout.html'), name='logout'),
    re_path(r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
            auth.Verify.as_view(), name='verify'),
    path('password/reset/', dj_auth.PasswordResetView.as_view(
        template_name='core/password_reset.html', success_url='/password/reset/done/', email_template_name='core/mail_password_reset.html'), name='password_reset'),
    path('password/reset/done/', dj_auth.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html', ), name='password_reset_done'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', dj_auth.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html', success_url='/password/reset/complete/'), name='password_reset_confirm'),
    path('password/reset/complete/', dj_auth.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html')),
    path('actor/set', auth.SetRole.as_view(), name='actor_set'),


    # locale stuff
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n.js', JavaScriptCatalog.as_view(
        packages=['recurrence']), name='jsi18n'),
]

src/resource_hub/plugins/sepa/urls.py
from django.urls import path

from resource_hub.core.urls import finance_urls

from .views import (OpenPayments, SEPAMandateDetails, XMLFilesCreate,
                    XMLFilesManage)

app_name = 'sepa'
finance_urls.register([
    path('sepa/mandate/<int:mandate_pk>/<int:contract_pk>/',
         SEPAMandateDetails.as_view(), name='sepa_mandate'),
    path('sepa/manage/', XMLFilesManage.as_view(),
         name='finance_sepa_files_manage'),
    path('sepa/create/', XMLFilesCreate.as_view(),
         name='finance_sepa_files_create'),
    path('sepa/payments/open/', OpenPayments.as_view(),
         name='finance_sepa_open_payments'),
])

urlpatterns = [
]

src/resource_hub/urls.py
"""
resource_hub URL Configuration

"""
import importlib

from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

for app in apps.get_app_configs():
    if importlib.util.find_spec(app.name + '.urls'):
        importlib.import_module(app.name + '.urls')

urlpatterns = [
    # apps
    path('', include('resource_hub.core.urls')),
    path('api/', include('resource_hub.api.urls')),
    path('control/', include('resource_hub.control.urls')),
    path('venues/', include('resource_hub.venues.urls')),
    path('items/', include('resource_hub.items.urls')),
    path('workshops/', include('resource_hub.workshops.urls')),

    # external apps
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/resource_hub/core/models/assets.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from .base import BaseModel, Gallery, Location
from .finance import Price


class AssetMixin(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name=_('Name'),
    )
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        verbose_name=_('UUID'),
    )
    slug = models.SlugField(
        db_index=True,
        max_length=50,
        verbose_name=_('Slug'),
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('Description'),
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        verbose_name=_('Location'),
        help_text=_('All public and current role\'s locations'),
    )
    thumbnail_original = models.ImageField(
        null=False,
        upload_to='images/',
        verbose_name=_('Thumbnail'),
        default='images/default.png',
    )
    thumbnail = ImageSpecField(
        source='thumbnail_original',
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 70},
    )
    gallery = models.ForeignKey(
        Gallery,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_('Gallery'),
    )
    base_price = models.ForeignKey(
        Price,
        null=True,
        on_delete=models.PROTECT,
        verbose_name=_('Base price'),
    )

    class Meta:
        abstract = True


class BaseAsset(AssetMixin, BaseModel):
    class Meta:
        abstract = True

src/resource_hub/core/views/api.py
from django.db import transaction
from django.db.models import Q
from django.shortcuts import get_list_or_404
from django.utils.translation import gettext_lazy as _

from resource_hub.core.models import Contract, Location, Notification, User
from resource_hub.core.serializers import (ActorSerializer, ContractSerializer,
                                           LocationSerializer,
                                           NotificationSerializer,
                                           UserSerializer)
from rest_framework import filters, generics
from rest_framework.decorators import (authentication_classes,
                                       permission_classes)
from rest_framework.exceptions import ValidationError
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import OrganizationMember
from ..utils import get_authorized_actors


class SmallResultsSetPagination(PageNumberPagination):
    page_size = 9
    page_size_query_param = 'page_size'
    max_page_size = 1000


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 12
    page_size_query_param = 'page_size'
    max_page_size = 1000


class NotificationResultsSetPagination(PageNumberPagination):
    page_size = 5
    page_size_query_param = 'page_size'
    max_page_size = 1000


class UserSearch(generics.ListCreateAPIView):
    http_method_names = ['get']
    search_fields = ['username', 'first_name', 'last_name']
    filter_backends = (filters.SearchFilter,)
    queryset = User.objects.all()
    serializer_class = UserSerializer


class ActorList(generics.ListCreateAPIView):
    http_method_names = ['get']
    serializer_class = ActorSerializer

    def get_queryset(self):
        return get_authorized_actors(self.request.user)


class ActorChange(APIView):
    def post(self, request, format=None):
        data = request.POST
        return Response(data)


@authentication_classes([])
@permission_classes([])
class Locations(generics.ListCreateAPIView):
    http_method_names = ['get']
    queryset = Location.objects.filter(is_public=True).order_by('-updated_at')
    serializer_class = LocationSerializer


class ContractsList(generics.ListCreateAPIView):
    http_method_names = ['get']
    serializer_class = ContractSerializer
    pagination_class = SmallResultsSetPagination

    def get_queryset(self):
        contract_type = self.request.query_params.get('type', None)
        if contract_type is None:
            raise ValidationError('type argument is not set')

        if contract_type == 'creditor':
            query = Q(creditor=self.request.actor)
        elif contract_type == 'debitor':
            query = Q(debitor=self.request.actor)
        else:
            raise ValidationError('invalid type argument')

        return Contract.objects.filter(query).select_subclasses().order_by('-created_at')


class NotificationsList(generics.ListCreateAPIView):
    http_method_name = ['get']
    serializer_class = NotificationSerializer
    pagination_class = NotificationResultsSetPagination

    def get_queryset(self):
        actor = self.request.actor
        return Notification.objects.filter(recipient=actor).order_by('-created_at')


class NotificationsUnread(APIView):
    def get(self, request):
        actor = request.actor
        data = {
            'count': Notification.objects.filter(is_read=False, recipient=actor).count(),
        }
        return Response(data)


class NotificationsMarkRead(APIView):
    def put(self, request):
        pk = request.POST.get('pk')
        actor = request.actor
        query = Q(pk=pk, recipient=actor) if pk else Q(recipient=actor)
        Notification.objects.filter(query).update(is_read=True)
        return Response({'detail': 'updated notification status as read'})


class OrganizationMembersChange(APIView):
    def post(self, request, organization_pk):
        owners = len(get_list_or_404(
            OrganizationMember,
            role=OrganizationMember.OWNER,
            organization=organization_pk
        ))
        with transaction.atomic():
            for pk, data in request.data.items():
                member = OrganizationMember.objects.filter(
                    pk=pk
                )
                if 'role' in data:
                    role = int(data['role'])
                    if role != OrganizationMember.OWNER and member[0].role == OrganizationMember.OWNER:
                        owners -= 1
                    if role == OrganizationMember.OWNER and member[0].role != OrganizationMember.OWNER:
                        owners += 1
                member.update(**data)
            if owners <= 0:
                raise ValidationError(
                    detail=_('There has to be at least one owner!'))
        return Response({'detail': 'updated notification status as read'})

src/resource_hub/core/views/site.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View

from resource_hub.core.forms import ActorForm, ReportBugForm
from resource_hub.core.models import Actor, Location

from ..utils import get_site_info


def index(request):
    return redirect(reverse('core:home'))


class Home(View):
    def get(self, request):
        return render(request, 'core/home.html')


class Terms(View):
    def get(self, request):
        return render(request, 'core/terms_and_conditions.html', get_site_info())


class DataPrivacyStatement(View):
    def get(self, request):
        return render(request, 'core/data_privacy_statement.html', get_site_info())


class Imprint(View):
    def get(self, request):
        return render(request, 'core/imprint.html', get_site_info())


class ReportBug(View):
    template_name = 'core/report_bug.html'
    context = {
        'bug_form': ReportBugForm(),
    }

    def get(self, request):
        return render(request, self.template_name, self.context)

    def post(self, request):
        bug_form = ReportBugForm(request.POST)

        if bug_form.is_valid():
            bug_form.post()
            message = _('Your issue has been posted!')
            messages.add_message(request, messages.SUCCESS, message)

            return redirect(reverse('core:report_bug'))

        self.context['bug_form'] = bug_form
        return render(request, self.template_name, self.context)


class Language(View):
    def get(self, request):
        return render(request, 'core/language.html')


class ActorProfile(View):
    def get(self, request, slug):
        actor = get_object_or_404(Actor, slug=slug)
        context = {
            'actor': actor,
        }
        return render(request, 'core/actor_profile.html', context)


class LocationsProfile(View):
    def get(self, request, slug):
        location = get_object_or_404(Location, slug=slug)
        context = {
            'location': location
        }
        return render(request, 'core/locations_profile.html', context)

src/resource_hub/core/templates/core/__base.html
{% extends "__base.html" %}
{% load i18n %}

{% block main %}
{% block not_in_container %}
{% endblock %}
<div class="main container">
    {% include "_messages.html" %}
    {% block content %}
    {% endblock %}
</div>
{% endblock %}


{% block footer %}
{% include '_footer.html' %}
{% endblock %}

src/resource_hub/core/templates/core/_identity.html
{% load i18n %}
<div class="ui icon message">
    <i class="id card icon"></i>
    <div class="contetn">
        <div class="header">{% trans 'Your current role is' %} {{ actor.name }}</div>
        <p>{% trans 'The actions you take will be attributed to this entity!' %}</p>
    </div>
</div>

src/resource_hub/core/templates/core/_navbar_items.html
{% for item in structure %}
<a class="item" href="{{ item.url }}">
    {{ item.header }}
</a>
{% endfor %}

src/resource_hub/core/templates/core/actor_profile.html
{% extends "core/__base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<h1>
    {% trans 'Profile' %}
</h1>
<div class="section-container tab-content">
    <div class="ui stackable two column grid">
        <div class="twelve wide column">
            <h1>
                {{ actor.name }}
            </h1>
            <div class="ui container">
                <label class="ui tiny header">{% trans 'description' %}</label>
                <p>
                    {{ actor.info_text| safe }}
                </p>
                <label class="ui tiny header">{% trans 'telephone (public)' %}</label>
                <p>
                    {{ actor.telephone_public }}
                </p>
                <label class="ui tiny header">{% trans 'email (public)' %}</label>
                <p>
                    {{ actor.email_public }}
                </p>
                <label class="ui tiny header">{% trans 'website' %}</label>
                <p>
                    <a href="{{ actor.website }}">{{ actor.website }}</a>
                </p>
            </div>
        </div>
        <div class="four wide column">
            <div class="ui container center aligned">
                <img width="100%" alt="{% trans 'Logo' %}" src="
                    {% if actor.thumbnail_large %}
                    {{ actor.thumbnail_large.url }}
                    {% else %}
                    {% static 'default.png' %}
                    {% endif %}
                    ">
            </div>

        </div>
    </div>
</div>
{% endblock %}

src/resource_hub/core/templates/core/home.html
{% extends "core/__base.html" %}
{% load i18n %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}">
<script src="{% static 'leaflet/leaflet.js' %}"></script>
<script src="{% static 'bouncemarker/bouncemarker.js' %}"></script>
{% endblock %}

{% block not_in_container %}
{% include '_support-button.html' %}
{% include '_map.html' %}
{% endblock %}

{% block content %}
<h1>{% trans 'Locations' %}</h1>
{% include '_block_feed.html' with blocks='three' %}
{% endblock %}

{% block scripts %}
<script id="popup-template" type="text/tempate">
    <h5>%name%</h5>
    <p><i class="map marker alternate icon"></i>%address_string%</p>
    <a class="ui positive button" href="%location_link%">{% trans 'Details' %}</a>
</script>

<script id="location-item-template" type="text/template">
<div class="column">
    <a id='card' class="ui fluid card" href="%location_link%">
        <div class="content">
            <img class="ui avatar image" src="%owner_thumbnail%" alt="{% trans 'Logo' %}"> %owner_name%
        </div>
        <div class="blurring dimmable image">
            <div class="ui dimmer">
                <div class="content">
                    <div class="center">
                        <div class="ui inverted button">{% trans 'Details' %}</div>
                    </div>
                </div>
            </div>
            <img class="thumbnail" src="%location_thumbnail%" alt="{% trans 'Thumbnail' %}">
        </div>
        <div class="ui placeholder">
            <div class="square image"></div>
        </div>
        <div class="content">
            <div class="header">%location_name%</div>
            <div class="meta">
                <p><i class="map marker alternate icon"></i> %address_string%</p>
            </div>
        </div>
    </a>
</div>
</script>

<script>
    function render_location_feed(data) {
        var feed = "";
        var template = document.getElementById("location-item-template");
        var templateHtml = template.innerHTML;

        $.each(data, function (i, location) {
            feed += templateHtml
                .replace(/%owner_name%/g, location.owner['name'])
                .replace(/%owner_thumbnail%/g, location.owner['thumbnail'])
                .replace(/%location_link%/g, location['location_link'])
                .replace(/%location_thumbnail%/g, location['thumbnail'])
                .replace(/%location_name%/g, location.name)
                .replace(/%address_string%/g, location.address['address_string']);

            location_markers(location);
        });
        return feed;

    }

    function location_markers(location) {
        var popup_template = document.getElementById('popup-template').innerHTML;
        var popup = popup_template
            .replace(/%name%/g, location.name)
            .replace(/%address_string%/g, location.address.address_string)
            .replace(/%location_link%/g, location['location_link']);
        L.marker([location.latitude, location.longitude], {
            bounceOnAdd: true,
            bounceOnAddOptions: { duration: 500, height: 70 },
            icon: marker,
            title: location.name,
            clickable: true,
        }).bindPopup(popup).addTo(map);
    }

    $(document).ready(function () {
        var feed = new BlockFeed('{% url "api:locations_search" %}', 'feed', render_location_feed);
        feed.create_feed();
    });
</script>
{% endblock %}

src/resource_hub/core/templates/core/login.html
{% extends "core/__base.html" %}
{% load i18n %}

{% block content %}
<div class="">
    <h1>Login</h1>
    <div class="section-container">
        <form class="ui form" method="post">
            {% csrf_token %}
            {% include "_form.html" with form=form %}
            <button class="ui positive right labeled icon button" type="submit">
                {% trans 'Login' %}
                <i class="sign-in icon"></i>
            </button>
            <a class="ui primary right labeled icon right floated button" href="{% url 'core:register' %}">
                {% trans 'Register' %}
                <i class="clipboard outline icon"></i>
            </a>
        </form>
    </div>
    <a class="ui grey button" href="{% url 'core:password_reset' %}">
        {% trans 'Forgot password?' %}
    </a>
</div>
{% endblock %}

src/resource_hub/core/templates/core/logout.html
{% extends "core/__base.html" %}
{% load i18n %}
{% block content %}




<div class="ui placeholder segment">
    <div class="ui icon header">
        <i class="sign out alternate icon"></i>
        <p>{% trans 'logged out!' %}</p>
        <a href="{% url 'core:login'%}">
            {% trans 'click here to log in again' %}
        </a>
    </div>
</div>

{% endblock %}

src/resource_hub/core/templates/core/mail_invitation.html
{% extends '__mail.html' %}
{% load i18n %}

{% block content %}
<p>
    Hi!
</p>
<p>
    {% blocktrans with organization=invitation.organization invitee=invitation.invitee %}
    You have been invited by {{ invitee }} to join {{ organization }}. Click
    this link to sign up
    and follow the invitation:
    <br />
    <a href="{{ link }}">{{ link }}</a>
    {% endblocktrans %}
</p>
<p>
    {{ invitation.text|safe }}
</p>
{% endblock %}

src/resource_hub/core/templates/core/mail_verification.html
{% extends '__mail.html' %}
{% load i18n %}

{% block content %}
<p>
    Hi, {{ user.first_name }}!
</p>
<p>
    {% trans "Thank you for signing up. Before you can get started you need to verify your email. Just click the link below." %}
</p>
<p>
    <a href="{{ link }}">
        {% trans 'activate account' %}
    </a>
</p>
{% endblock %}

src/resource_hub/core/templates/core/password_reset.html
{% extends "core/__base.html" %}
{% load i18n %}

{% block content %}
<div class="">
    <h1>{% trans 'reset your password' %}</h1>
    <div class="section-container">
        <form class="ui form" method="post">
            {% include "_form.html" with form=form %}
            <button class="ui positive right labeled icon button" type="submit">
                {% trans 'reset' %}
                <i class="check icon"></i>
            </button>
        </form>
    </div>
</div>
{% endblock %}

src/resource_hub/core/templates/core/password_reset_confirm.html
{% extends "core/__base.html" %}
{% load i18n %}

{% block content %}
{% if validlink %}
<div class="section-container">
    <p>{% trans 'please enter (and confirm) your new password.' %}</p>
    <form class="ui form" action="" method="post">
        {% include '_form.html' with form=form %}
        <button class="ui positive right labeled icon button" type="submit">
            {% trans 'confirm' %}
            <i class="check icon"></i>
        </button>

    </form>
    {% else %}
    <h1>{% trans 'password reset failed' %}</h1>
    <p>{% trans 'the password reset link was invalid, possibly because it has already been used. Please request a new password
        reset.' %}
    </p>
    {% endif %}
</div>
{% endblock %}

src/resource_hub/core/templates/core/password_reset_done.html
{% extends "core/__base.html" %}
{% load i18n %}

{% block content %}
<div class="">
    <h1>{% trans 'reset done' %}</h1>
    <div class="section-container">
        <p>{% blocktrans %}
            We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check
            your spam folder.
            {% endblocktrans %}
        </p>
    </div>
</div>
{% endblock %}

src/resource_hub/core/templates/core/register.html
{% extends "core/__base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<h1>{% trans 'Register' %}</h1>
<div class="segment-container">
    <form class="ui form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "_form.html" with form=user_form %}

        <h3>{% trans 'Optional information' %}</h3>
        <small>{% trans 'This information may become required later' %}</small>
        <div class="ui accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b>{% trans 'Show' %}</b>
            </div>
            <div class="content">
                <h3>{% trans 'Billing address' %}</h3>
                {% include "_form.html" with form=address_form %}

                <h3>{% trans 'Bank account' %}</h3>
                {% include "_form.html" with form=bank_account_form %}
            </div>
        </div>

        <p>
            <a href="{% url 'core:terms' %}" target="_blank">
                <i class="file icon"></i>
                {% trans 'Show the terms and conditions' %}
            </a>
        </p>
        <div class="ui slider checkbox">
            <input type="checkbox" name="terms" required>
            <label for="terms">
                <b>
                    {% trans 'I fully understand and agree to the given terms and conditions.' %}
                </b>
            </label>
        </div>
        <p>
            <a href="{% url 'core:privacy' %}" target="_blank">
                <i class="file icon"></i>
                {% trans 'Show the data privacy statement' %}
            </a>
        </p>
        <div class="ui slider checkbox">
            <input id="privacy" type="checkbox" name="privacy" required>
            <label for="privacy">
                <b>
                    {% trans 'I fully understand and agree to the given data privacy statement' %}
                </b>
            </label>
        </div>
        <p>
            <button class="ui positive right labeled icon button" type="submit">
                {% trans 'Sign up' %}
                <i class="checkmark icon"></i>
            </button>
        </p>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script language='javascript'>
    $(document).ready(function () {
        $('.ui.accordion').accordion();
    });
</script>
{% endblock %}